# Create persistent volume for mysql
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
  storageClassName: standard
  hostPath:
    path: /Users/himanshu/Desktop/ResumeTool/mysql/data
    type: DirectoryOrCreate